# Generated by Django 6.0.6 on 2026-06-23 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentaccesslog',
            options={'ordering': ['-downloaded_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organisation_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Organisation share from this payment e.g. 90% of amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform cut from this payment e.g. 10% of amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_percentage_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The percentage that was applied at time of payment', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paystack_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paystack_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
