# Generated by Django 4.2.7 on 2026-06-22 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appraisal Category',
                'verbose_name_plural': 'Appraisal Categories',
            },
        ),
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('download_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount in Naira employees pay to download their appraisal PDF', max_digits=10)),
                ('part1_deadline', models.DateField(blank=True, null=True)),
                ('part2_deadline', models.DateField(blank=True, null=True)),
                ('part3_deadline', models.DateField(blank=True, null=True)),
                ('part4_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='hr.appraisalcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appraisal Cycle',
                'verbose_name_plural': 'Appraisal Cycles',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Appraisal Template',
                'verbose_name_plural': 'Appraisal Templates',
            },
        ),
        migrations.CreateModel(
            name='PerformanceAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('outstanding_description', models.TextField(help_text='Description for rating A (Outstanding)')),
                ('unsatisfactory_description', models.TextField(help_text='Description for rating E (Unsatisfactory)')),
                ('is_applicable', models.BooleanField(default=True, help_text='Uncheck if this aspect does not apply to certain staff')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the display order on the form')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Aspect',
                'verbose_name_plural': 'Performance Aspects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.performanceaspect')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.appraisaltemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'aspect')},
            },
        ),
        migrations.AddField(
            model_name='appraisaltemplate',
            name='aspects',
            field=models.ManyToManyField(related_name='templates', through='hr.TemplateAspect', to='hr.performanceaspect'),
        ),
        migrations.AddField(
            model_name='appraisaltemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisaltemplate',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='hr.appraisalcycle'),
        ),
    ]
