# Generated by Django 6.0.6 on 2026-06-23 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalcategory',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='appraisalcycle',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='appraisaltemplate',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='performanceaspect',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Null means this is a platform default aspect available to all', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aspects', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='appraisalcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appraisalcycle',
            name='download_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount in Naira employees pay to download their PDF', max_digits=10),
        ),
        migrations.AlterField(
            model_name='performanceaspect',
            name='is_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='performanceaspect',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performanceaspect',
            name='outstanding_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='performanceaspect',
            name='unsatisfactory_description',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='appraisalcategory',
            unique_together={('organisation', 'name')},
        ),
    ]
