# Generated by Django 6.0.6 on 2026-06-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Which organisation does this user belong to?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='organisations.organisation'),
        ),
    ]
