# Generated by Django 4.2.7 on 2026-06-22 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('part1_submitted', 'Part 1 Submitted'), ('part2_submitted', 'Part 2 Submitted'), ('part3_submitted', 'Part 3 Submitted'), ('completed', 'Completed'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('part1_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('part2_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('part3_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('part4_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='hr.appraisalcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='hr.appraisaltemplate')),
            ],
            options={
                'verbose_name': 'Appraisal',
                'verbose_name_plural': 'Appraisals',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='PartTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrees_with_job_description', models.BooleanField(default=True, verbose_name='Do you agree with the job description?')),
                ('job_description_disagreement', models.TextField(blank=True, verbose_name='If NO, state unresolved differences')),
                ('performance_assessment', models.TextField(help_text='How effective is he/she in the performance of duties set out in 11(a)?', verbose_name='Assessment of Performance')),
                ('rating_foresight', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_penetration', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_judgement', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_expression_paper', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_oral_expression', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_numerical_ability', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_relations_colleagues', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_relations_public', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_acceptance_responsibility', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_reliability_pressure', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_drive_determination', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_professional_knowledge', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_management_staff', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2, verbose_name='Management of Staff (if applicable)')),
                ('rating_output_of_work', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_quality_of_work', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('rating_punctuality', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2)),
                ('overall_rating', models.CharField(choices=[('1', '1 - Outstanding'), ('2', '2 - Very Good'), ('3', '3 - Good'), ('4', '4 - Fair'), ('5', '5 - Unsatisfactory')], max_length=1, verbose_name='Overall Performance Rating')),
                ('reporting_officer_grade', models.CharField(max_length=100)),
                ('reporting_officer_job_title', models.CharField(max_length=200)),
                ('years_known', models.PositiveIntegerField(default=0, help_text='He has served under me for the past X years')),
                ('is_draft', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part_two', to='appraisal.appraisal')),
                ('reporting_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_two_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_needs', models.TextField(blank=True, help_text='If performance could be improved by training, specify the needs', verbose_name='Training Needs')),
                ('training_how_met', models.TextField(blank=True, help_text='If they cannot be met on the job, suggest how they might be met', verbose_name='How Training Needs Can Be Met')),
                ('different_job_same_grade', models.BooleanField(default=False, verbose_name='Should be considered for a different job in the same grade')),
                ('transfer_to_another_cadre', models.BooleanField(default=False, verbose_name='Transfer to a job at similar level in another cadre')),
                ('next_job_reasons', models.TextField(blank=True, verbose_name='Reasons for next job recommendation')),
                ('promotion_fitness', models.CharField(blank=True, choices=[('well_fitted', 'Well Fitted'), ('fitted', 'Fitted'), ('not_fitted', 'Not Fitted')], max_length=15)),
                ('promotion_to_grade', models.CharField(blank=True, max_length=100, verbose_name='Promotion to Grade')),
                ('promotion_comment', models.TextField(blank=True, verbose_name='Comment on promotion recommendation')),
                ('special_promotion_grade', models.CharField(blank=True, max_length=100, verbose_name='Special promotion to Grade')),
                ('special_promotion_reasons', models.TextField(blank=True, verbose_name='Reasons for special promotion recommendation')),
                ('long_term_potential', models.CharField(blank=True, choices=[('1', '1 - Unlikely to progress further'), ('2', '2 - Potential to rise about one grade but probably no further'), ('3', '3 - Potential to rise two or three grades'), ('4', '4 - Exceptional potential')], max_length=1)),
                ('general_remarks', models.TextField(blank=True, help_text='Additional relevant information, strengths or weaknesses', verbose_name='General Remarks')),
                ('years_served_under_reporting_officer', models.PositiveIntegerField(default=0)),
                ('reporting_officer_grade', models.CharField(blank=True, max_length=100)),
                ('reporting_officer_name', models.CharField(blank=True, max_length=200)),
                ('is_draft', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part_three', to='appraisal.appraisal')),
                ('reporting_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_three_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.TextField(help_text='Degree, Diploma, Certificate etc. Underline those acquired during report period')),
                ('date_of_first_appointment', models.DateField()),
                ('present_substantive_grade', models.CharField(max_length=100)),
                ('date_appointed_to_grade', models.DateField()),
                ('acting_appointment', models.TextField(blank=True, help_text='Acting appointment held during period of report')),
                ('courses_undertaken', models.TextField(blank=True, help_text='Courses undertaken during period of report')),
                ('days_absent_sick', models.PositiveIntegerField(default=0, help_text='Total number of days absent on sick leave during period of report')),
                ('present_job', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('main_duty_1', models.TextField(blank=True, verbose_name='Main Duty 1')),
                ('main_duty_2', models.TextField(blank=True, verbose_name='Main Duty 2')),
                ('main_duty_3', models.TextField(blank=True, verbose_name='Main Duty 3')),
                ('main_duty_4', models.TextField(blank=True, verbose_name='Main Duty 4')),
                ('main_duty_5', models.TextField(blank=True, verbose_name='Main Duty 5')),
                ('adhoc_duties', models.TextField(blank=True, help_text='Any adhoc duties performed which are not of a continuous nature')),
                ('is_draft', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part_one', to='appraisal.appraisal')),
            ],
        ),
        migrations.CreateModel(
            name='PartFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countersigning_report', models.TextField(help_text='Confirm agreement or indicate disagreements with reporting officer assessment', verbose_name="Countersigning Officer's Report")),
                ('years_served_under_countersigning', models.PositiveIntegerField(default=0)),
                ('countersigning_grade', models.CharField(blank=True, max_length=100)),
                ('countersigning_name', models.CharField(blank=True, max_length=200)),
                ('is_draft', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part_four', to='appraisal.appraisal')),
                ('countersigning_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countersigned_appraisals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppraisalAspectRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], max_length=2)),
                ('comment', models.TextField(blank=True)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.performanceaspect')),
                ('part_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect_ratings', to='appraisal.parttwo')),
            ],
            options={
                'unique_together': {('part_two', 'aspect')},
            },
        ),
    ]
