# Generated by Django 6.0.6 on 2026-06-23 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='appraisal',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='partfour',
            name='countersigning_report',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partone',
            name='acting_appointment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partone',
            name='adhoc_duties',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partone',
            name='courses_undertaken',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partone',
            name='days_absent_sick',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partone',
            name='main_duty_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partone',
            name='main_duty_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partone',
            name='main_duty_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partone',
            name='main_duty_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partone',
            name='main_duty_5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partone',
            name='qualification',
            field=models.TextField(help_text='Degree, Diploma, Certificate etc.'),
        ),
        migrations.AlterField(
            model_name='partthree',
            name='different_job_same_grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partthree',
            name='general_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partthree',
            name='next_job_reasons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partthree',
            name='promotion_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partthree',
            name='promotion_to_grade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partthree',
            name='special_promotion_grade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partthree',
            name='special_promotion_reasons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partthree',
            name='training_how_met',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partthree',
            name='training_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partthree',
            name='transfer_to_another_cadre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='agrees_with_job_description',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='job_description_disagreement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='overall_rating',
            field=models.CharField(choices=[('1', '1 - Outstanding'), ('2', '2 - Very Good'), ('3', '3 - Good'), ('4', '4 - Fair'), ('5', '5 - Unsatisfactory')], max_length=1),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='performance_assessment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='rating_management_staff',
            field=models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='years_known',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
