# Generated by Django 6.0.6 on 2026-06-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_alter_appraisal_options_appraisal_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partone',
            name='date_appointed_to_grade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partone',
            name='date_of_first_appointment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
