# Generated by Django 6.0.6 on 2026-06-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0003_alter_partone_date_appointed_to_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_acceptance_responsibility',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_drive_determination',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_expression_paper',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_foresight',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_judgement',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_management_staff',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_numerical_ability',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_oral_expression',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_output_of_work',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_penetration',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_professional_knowledge',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_punctuality',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_quality_of_work',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_relations_colleagues',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_relations_public',
        ),
        migrations.RemoveField(
            model_name='parttwo',
            name='rating_reliability_pressure',
        ),
        migrations.AlterField(
            model_name='appraisalaspectrating',
            name='rating',
            field=models.CharField(choices=[('A', 'A - Outstanding'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E - Unsatisfactory'), ('NA', 'Not Applicable')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='agrees_with_job_description',
            field=models.BooleanField(default=True, verbose_name='Do you agree with the job description?'),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='job_description_disagreement',
            field=models.TextField(blank=True, verbose_name='If NO, state unresolved differences'),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='overall_rating',
            field=models.CharField(choices=[('1', '1 - Outstanding'), ('2', '2 - Very Good'), ('3', '3 - Good'), ('4', '4 - Fair'), ('5', '5 - Unsatisfactory')], max_length=1, verbose_name='Overall Performance Rating'),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='performance_assessment',
            field=models.TextField(help_text='How effective is he/she in the performance of duties set out in 11(a)?', verbose_name='Assessment of Performance'),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='reporting_officer_grade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='reporting_officer_job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='parttwo',
            name='years_known',
            field=models.PositiveIntegerField(default=0, help_text='He has served under me for the past X years'),
        ),
    ]
