# Generated by Django 6.0.6 on 2026-06-23 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full official name e.g. Federal Ministry of Finance', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL identifier e.g. federal-ministry-of-finance', max_length=200, unique=True)),
                ('acronym', models.CharField(blank=True, help_text='Short form e.g. FMF, FIRS, NNPC', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Official contact email of the organisation', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Organisation logo shown on appraisal PDF', null=True, upload_to='org_logos/')),
                ('subscription_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform percentage from each employee PDF download e.g. 10 means 10%', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive organisations cannot access the system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
    ]
